- name: Install and compile FAST
  hosts: all
  vars:
    home_dir: "/home/fast-bench"
  tasks:
    - name: Copy datasets
      ansible.builtin.copy:
        remote_src: true
        src: "/mnt/dbgroup-share/dschmitt/datasets/"
        dest: "{{ home_dir }}/datasets/"